M48
; DRILL file {KiCad (7.0.0)} date Sat Nov  4 11:59:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-04T11:59:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,Plated,1,2,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.400
%
G90
G05
T1
X81.407Y-33.401
X81.661Y-51.435
X87.503Y-51.689
X89.408Y-29.972
X90.07Y-27.74
T0
M30
