M48
; DRILL file {KiCad (7.0.0)} date Sat Nov  4 11:38:19 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-04T11:38:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,Plated,2,4,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T2C0.400
%
G90
G05
T1
X102.85Y-18.124
T2
X90.805Y-39.751
T0
M30
